version: "3"

x-uffizzi:
    ingress:
        service: nopcommerce_web
        port: 80

services:
    nopcommerce_web:
        image: "${NOPCOMMERCE_IMAGE}"
        ports:
            - "80:80"
        depends_on:
            - nopcommerce_database
    nopcommerce_database:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: nopcommerce_mssql_server
        environment:
            SA_PASSWORD: "nopCommerce_db_password"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"

volumes:
  nopcommerce_data:       